# Generated by Django 4.1.7 on 2023-03-16 18:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeatIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField()),
                ('humidity', models.IntegerField()),
                ('date', models.DateTimeField(default=datetime.datetime(2023, 3, 16, 19, 40, 0, 451875))),
            ],
        ),
    ]
